//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSPEmailTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWSPEmailTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aligncenter {
            get {
                object obj = ResourceManager.GetObject("aligncenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignjustify {
            get {
                object obj = ResourceManager.GetObject("alignjustify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignleft {
            get {
                object obj = ResourceManager.GetObject("alignleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignright {
            get {
                object obj = ResourceManager.GetObject("alignright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bold {
            get {
                object obj = ResourceManager.GetObject("bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClearFormatting16 {
            get {
                object obj = ResourceManager.GetObject("ClearFormatting16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DocumentInfo {
            get {
                object obj = ResourceManager.GetObject("DocumentInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EnableSpellCheck {
            get {
                object obj = ResourceManager.GetObject("EnableSpellCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit1 {
            get {
                object obj = ResourceManager.GetObject("exit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap font_decreasesize {
            get {
                object obj = ResourceManager.GetObject("font_decreasesize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap font_increasesize {
            get {
                object obj = ResourceManager.GetObject("font_increasesize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fontcolor {
            get {
                object obj = ResourceManager.GetObject("fontcolor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap formatting_symbols {
            get {
                object obj = ResourceManager.GetObject("formatting_symbols", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap highlight {
            get {
                object obj = ResourceManager.GetObject("highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Html {
            get {
                object obj = ResourceManager.GetObject("Html", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_icon {
            get {
                object obj = ResourceManager.GetObject("import_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap indent {
            get {
                object obj = ResourceManager.GetObject("indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap italic {
            get {
                object obj = ResourceManager.GetObject("italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap list_bullets {
            get {
                object obj = ResourceManager.GetObject("list_bullets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap list_numbered {
            get {
                object obj = ResourceManager.GetObject("list_numbered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MultilevelList {
            get {
                object obj = ResourceManager.GetObject("MultilevelList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap outdent {
            get {
                object obj = ResourceManager.GetObject("outdent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageMarginModerate {
            get {
                object obj = ResourceManager.GetObject("PageMarginModerate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageMarginNarrow {
            get {
                object obj = ResourceManager.GetObject("PageMarginNarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageMarginNormal {
            get {
                object obj = ResourceManager.GetObject("PageMarginNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageOrientationLandscape {
            get {
                object obj = ResourceManager.GetObject("PageOrientationLandscape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageOrientationPortrait {
            get {
                object obj = ResourceManager.GetObject("PageOrientationPortrait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageOrientationRotate180 {
            get {
                object obj = ResourceManager.GetObject("PageOrientationRotate180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageOrientationRotate270 {
            get {
                object obj = ResourceManager.GetObject("PageOrientationRotate270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageSize {
            get {
                object obj = ResourceManager.GetObject("PageSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ParagraphBackgroundColor {
            get {
                object obj = ResourceManager.GetObject("ParagraphBackgroundColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pdf {
            get {
                object obj = ResourceManager.GetObject("Pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlainText {
            get {
                object obj = ResourceManager.GetObject("PlainText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string Prantez_close {
            get {
                return ResourceManager.GetString("Prantez_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string Prantez_open {
            get {
                return ResourceManager.GetString("Prantez_open", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] RichTextBox_for_WinForms_Beta {
            get {
                object obj = ResourceManager.GetObject("RichTextBox_for_WinForms_Beta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RichTextBox_Overview {
            get {
                object obj = ResourceManager.GetObject("RichTextBox_Overview", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rtf {
            get {
                object obj = ResourceManager.GetObject("Rtf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as1 {
            get {
                object obj = ResourceManager.GetObject("save_as1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save1 {
            get {
                object obj = ResourceManager.GetObject("save1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Strikethrough16 {
            get {
                object obj = ResourceManager.GetObject("Strikethrough16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap subscript {
            get {
                object obj = ResourceManager.GetObject("subscript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap superscript {
            get {
                object obj = ResourceManager.GetObject("superscript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_05 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_051 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_051", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_07 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_071 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_071", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_09 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_091 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_091", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_16 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_17 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_171 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_171", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_172 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_172", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_173 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_173", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_18 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_181 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_182 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_182", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_183 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_183", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_19 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_191 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_191", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_20 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_21 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_211 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_211", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_24 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_28 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_31 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_32 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_34 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_39 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_41 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_52 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_521 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_61 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_76 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_79 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_79", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_83 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_83", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_87 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_92 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_92", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWSPETSYSTEMSTYLE1_93 {
            get {
                object obj = ResourceManager.GetObject("SWSPETSYSTEMSTYLE1_93", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the system will try to fetch data from your server, so be patient..
        /// </summary>
        internal static string TemplateManager_TemplateManager_Load_the_system_will_try_to_fetch_data_from_your_server__so_be_patient_ {
            get {
                return ResourceManager.GetString("TemplateManager_TemplateManager_Load_the_system_will_try_to_fetch_data_from_your_" +
                        "server__so_be_patient_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap underline {
            get {
                object obj = ResourceManager.GetObject("underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap worddoc {
            get {
                object obj = ResourceManager.GetObject("worddoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Xaml {
            get {
                object obj = ResourceManager.GetObject("Xaml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
